- hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"
  tasks:
   - name: Device group table creation.
     fmgr_dvmdb_group:
        bypass_validation: False
        adom: root
        state: present
        dvmdb_group:
           desc: 'ansible-test'
           name: 'HUBs'  # Device group name
           os_type: fos
           type: normal

   - name: Add device to device group
     fmgr_dvmdb_group_member:
        bypass_validation: False
        adom: root
        state: present
        dvmdb_group_member:
           group_name: 'HUBs'  # Device group name
           device_name: 'Hub'  # Device name to add to the group
