- hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"
  tasks:
    - name: Configure dynamic mappings of IPv4 address group
      fortinet.fortimanager.fmgr_firewall_addrgrp_dynamicmapping:
        bypass_validation: false
        adom: root
        addrgrp: "HUBs" # name
        state: present
        firewall_addrgrp_dynamicmapping:
          _scope:
            - name: Hub # need a valid device name
              vdom: root # need a valid vdom name under the device
          allow-routing: disable
          color: 1
          member: "ansible-test1"
          visibility: enable