---
- name: Configure FortiManager User Device Group
  hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
    ansible_user: "admin"             # Required
    ansible_password: "admin"      # Required
    ansible_host: "192.168.10.6"
    ansible_collections_warnings: False  # Suppresses warnings

  tasks:
    - name: Configure dynamic mappings
      fmgr_user_devicegroup_dynamicmapping:
        adom: "ansible"
        device-group: "HUBs"
        state: "present"
        user_devicegroup_dynamicmapping:
          _scope:
            - name: "Hub"   # Must exist in FortiManager
              vdom: "root"       # Valid VDOM
          comment: "Ansible-managed"
          # member: "ios-device"  # Only include if needed

