---
- name: Configure FortiManager User Device Group
  hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"

  tasks:
    - name: CREATE DEVICE GROUP (if not exists)
      fortinet.fortimanager.fmgr_dvmdb_group:
        adom: "root"
        state: "present"
        dvmdb_group:
          name: "HUBs"

    - name: ADD DEVICE TO DEVICE GROUP (manually PATCH)
      fortinet.fortimanager.fmgr_generic:
        method: "update"
        url: "/dvmdb/adom/root/group/HUBs"
        params:
          - data:
              member:
                - name: "Hub"
