- hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"
    adom: "root"
    groups:
      HUB:
        - "Hub"
      spokes:
        - "spoke1"
        - "spoke2"
    vdom: "root"

  tasks:
    - name: Add devices to their respective groups
      fortinet.fortimanager.fmgr_dvmdb_group_objectmember:
        adom: "{{ adom }}"
        group: "{{ item.group }}"
        state: "present"
        proposed_method: "add"
        dvmdb_group_objectmember:
          name: "{{ item.name }}"
          vdom: "{{ vdom }}"
      loop: >
        [
          { "group": "HUBs", "name": "{{ groups.HUB | join(',') }}" },
          { "group": "spokes", "name": "{{ groups.spokes | join(',') }}" }
        ]
      loop_control:
        label: "{{ item.group }}"
