- hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    device_groups:
      - name: "HUBs"
        desc: "HUB devices"
      - name: "spokes"
        desc: "Spoke devices"

  tasks:
    - name: Create device groups for HUBs and spokes.
      fmgr_dvmdb_group:
        bypass_validation: False
        adom: root
        state: present
        dvmdb_group:
          desc: "{{ item.desc }}"
          name: "{{ item.name }}"
          os_type: fos
          type: normal
      loop: "{{ device_groups }}"
