- hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"
  tasks:
   - name: Configure device groups
     fmgr_user_devicegroup:
        bypass_validation: False
        workspace_locking_adom: root
        workspace_locking_timeout: 300
        rc_succeeded: [0, -2, -3]
        rc_failed: [-2, -3]
        adom: root
        state: present
        user_devicegroup:
           _if_unmanaged: 0
           comment: "Device group HUBs"
           dynamic_mapping: []
           member:
             - "Hub"  # Device name
           name: "HUBs"  # Device group name
