# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.25
# Label: user
# Desc: Configure dynamic mappings of device group
- hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"
  tasks:
   - name: Configure dynamic mappings of device group
     fmgr_user_devicegroup_dynamicmapping:
        bypass_validation: False
        adom: root
        device-group: HUBs 
        state: present
        user_devicegroup_dynamicmapping:
           _if_unmanaged: 10
           _scope:
             -
                 name: Hub # need a valid device name
                 vdom: root # need a valid vdom name under the device