- hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"
    adom: "root"
    HUB_devices:
      - "Hub"
    spoke_devices:
      - "spoke1"
      - "spoke2"
    vdom: "root"

  tasks:
    - name: Add devices to respective groups
      fortinet.fortimanager.fmgr_dvmdb_group_objectmember:
        adom: "{{ adom }}"
        group: "{{ item.group }}"
        state: "present"
        proposed_method: "add"
        dvmdb_group_objectmember:
          name: "{{ item.device }}"
          vdom: "{{ vdom }}"
      loop:
        - { group: "HUBs", device: "{{ HUB_devices  }}" }
        - { group: "spokes", device: "{{ spoke_devices }}" }
