- hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"

  tasks:
    - name: Add HUB device to the 'HUBs' group
      fortinet.fortimanager.fmgr_dvmdb_group_objectmember:
        adom: "root"
        group: "HUBs"
        state: "present"
        dvmdb_group_objectmember:
          name: "Hub"
          vdom: "root"

    - name: Add spoke devices to the 'spokes' group
      fortinet.fortimanager.fmgr_dvmdb_group_objectmember:
        adom: "root"
        group: "spokes"
        state: "present"
        dvmdb_group_objectmember:
          name: "{{ item }}"
          vdom: "root"
      loop:
        - "spoke1"
        - "spoke2"
