# Author: Xing Li
# Org: Fortinet
# Date: 2020.09.22
# Label: group
# Desc: Device group table

- hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"
  tasks:
   - name: Device group table.
     fmgr_dvmdb_group:
        bypass_validation: False
        adom: root
        state: present
        dvmdb_group:
           desc: 'ansible-test'
          #  meta fields: <value of string>
           name: 'ansible-test'
           os_type: fos
           type: normal