---
- name: Configure FortiManager User Device Group
  hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"


  tasks:
    - name: ADD DEVICES TO DEVICE GROUP
      fortinet.fortimanager.fmgr_device_group:
        mode: "add"
        grp_name: "HUBs"
        grp_members: "Hub"

