- hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"
  tasks:
    - name: Add device to the group
      fortinet.fortimanager.fmgr_dvmdb_group_objectmember:
        adom: "root"  # Administrative Domain, most likely "root"
        group: "HUBs"  # Name of the device group
        state: "present"  # To add the device to the group
        dvmdb_group_objectmember:
          name: "Hub"  # The device name
          vdom: "root"  # Virtual Domain (usually "root" unless custom VDOM is used)
    - name: Ensure Spoke devices are in the 'spokes' group (FMGR 2.9.1)
      fortinet.fortimanager.fmgr_dvmdb_group:
        adom: "root"
        group: "spokes"
        state: "present"
        members:
          - "{{ item }}"
        vdom: "root"   # ⚠️ Modifier si les VDOMs sont différents
      loop:
        - "spoke1"
        - "spoke2"
      ignore_errors: yes  # Continue même si un membre existe déjà
