---
- name: Set SD-WAN Template Scope Member in FortiManager
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    fortimanager_host: "192.168.10.6"
    fortimanager_username: "admin"
    fortimanager_password: "admin"
  tasks:
    - name: Authenticate with FortiManager to get session ID
      ansible.builtin.uri:
        url: "https://{{ fortimanager_host }}/jsonrpc"
        method: POST
        body_format: json
        body: >
          {
            "id": 1,
            "method": "exec",
            "params": [
              {
                "url": "/sys/login/user",
                "data": {
                  "user": "{{ fortimanager_username }}",
                  "passwd": "{{ fortimanager_password }}"
                }
              }
            ]
          }
        validate_certs: no
        status_code: 200
        return_content: yes
      register: login_response

    - name: Debug login response
      ansible.builtin.debug:
        var: login_response

    - name: Extract session ID
      ansible.builtin.set_fact:
        session_id: "{{ login_response.json.session }}"


    - name: Set scope member for SD-WAN template
      ansible.builtin.uri:
        url: "https://{{ fortimanager_host }}/jsonrpc"
        method: POST
        body_format: json
        body: >
          {
            "id": "291df3fd-954d-40f3-92fe-1cefd3dcce29",
            "method": "set",
            "params": [
              {
                "url": "pm/tmplgrp/adom/root/SD-WAN TEMPLATE_HUB1/scope member",
                "data": [
                  {"name": "HUBS", "is_group": 1}
                ]
              }
            ],
            "session": "{{ session_id }}"
          }
        headers:
          strict-origin-when-cross-origin: ""
        validate_certs: no
        status_code: 200
        return_content: yes
      register: result


    - name: Display response
      ansible.builtin.debug:
        var: result.json