---
- name: Set SD-WAN Template Scope Member in FortiManager
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    fortimanager_host: "192.168.10.6"
    fortimanager_username: "admin"
    fortimanager_password: "admin"
  tasks:
    - name: Authenticate with FortiManager to get session ID
      ansible.builtin.uri:
        url: "https://{{ fortimanager_host }}/jsonrpc"
        method: POST
        body_format: json
        body: >
          {
            "id": 1,
            "method": "exec",
            "params": [
              {
                "url": "/sys/login/user",
                "data": {
                  "user": "{{ fortimanager_username }}",
                  "passwd": "{{ fortimanager_password }}"
                }
              }
            ]
          }
        validate_certs: no
        status_code: 200
        return_content: yes
      register: login_response

    - name: Extract session ID
      ansible.builtin.set_fact:
        session_id: "{{ login_response.json.session }}"
      when: login_response.json.session is defined
    - name: Get SD-WAN templates
      ansible.builtin.uri:
        url: "https://{{ fortimanager_host }}/jsonrpc"
        method: POST
        body_format: json
        body: >
          {
            "id": 2,
            "method": "get",
            "params": [
              {
                "url": "pm/tmplgrp/adom/root"
              }
            ],
            "session": "{{ session_id }}"
          }
        validate_certs: no
        status_code: 200
        return_content: yes
      register: template_list
      when: session_id is defined

    - name: Debug template list
      ansible.builtin.debug:
        var: template_list.json