- name: Example playbook (generated based on argument schema)
  hosts: fortimanager
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
  tasks:
    - name: SET PROVISIONING TEMPLATE DEVICE TARGETS IN FORTIMANAGER
      community.fortios.fmgr_device_provision_template:
        provisioning_template: "SD-WAN Template_BRANCH"
        mode: "set"
        adom: "root"
        provision_targets: "spoke1, spoke2"