- name: Commit config to real device
  hosts: fortimanager
  gather_facts: false
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
    device_adom: "root"
    device_name: "Hub"
    device_vdom: "root"

  tasks:
    # - name: Invoke the task
    #   fortinet.fortimanager.fmgr_securityconsole_install_device:
    #     securityconsole_install_device:
    #       adom: "{{ device_adom }}"
    #       scope:
    #         - name: "{{ device_name }}"
    #           vdom: "{{ device_vdom }}"
    #   register: installing_task
    # - name: Inspect the Task Status
    #   fortinet.fortimanager.fmgr_fact:
    #     facts:
    #       selector: "task_task"
    #       params:
    #         task: "{{ installing_task.meta.response_data.task }}"
    #   register: taskinfo
    #   until: taskinfo.meta.response_data.percent == 100
    #   retries: 30
    #   delay: 3

    - name: Probe a remote device and retrieve its device information and system status.
      fortinet.fortimanager.fmgr_dvm_cmd_discover_device:
        bypass_validation: false
        dvm_cmd_discover_device:
          device:
            adm_pass: admin # device password
            adm_usr: admin # device user name
            ip: 172.21.0.254 # device ip
