- hosts: fortimanager
  collections:
    - community.fortios
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"
    adom: "root"
  tasks:
    - name: SET PROVISIONING TEMPLATE DEVICE TARGETS IN FORTIMANAGER
      community.fortios.fmgr_device_provision_template:
        provisioning_template: "SD-WAN Template_BRANCH"
        mode: "set"
        adom: "{{ adom }}"
        provision_targets: "spoke1, spoke2"
      register: result
      ignore_errors: true

    - name: Debug output
      debug:
        msg: "{{ result }}"