- hosts: fortimanager
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"
    adom: "root"
  tasks:
    - name: Set scope member for SD-WAN template
      community.fortios.fmgr_generic:
        host: "fortimanager.example.com"
        username: "admin"
        password: "password"
        adom: "root"
        method: "set"
        params:
          - url: "pm/tmplgrp/adom/root/SD-WAN TEMPLATE_HUB1/scope member"
            data:
              - name: "HUBS"
                is_group: 1
      register: result