---
- name: Install device settings only to a FortiGate
  hosts: fortimanager
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager

  vars:
    adom: "root"
    device_name: "Hub"  # change to your FortiGate's name in FortiManager

  tasks:
    - name: Trigger device settings install (device database only)
      fmgr_dvm_cmd_install:
        adom: "{{ adom }}"
        dvm_cmd_install:
          action: "install"
          flags:
            - "install_config"
          device:
            - name: "{{ device_name }}"
              vdom: "root"   # or your VDOM name
      register: install_result

    - name: Show result
      debug:
        var: install_result
