- hosts: fortimanager
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"
    adom: "root"
  tasks:
    - name: Set device provisioning template targets
      fortinet.fortios.fmgr_generic:
        method: "set"
        params:
          - url: "/pm/config/adom/{{ adom }}/template/device"
            data:
              name: "SD-WAN Template_BRANCH"
              provision_targets: ["spoke1", "spoke2"]