- name: Test connection
  hosts: fortimanager
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Test HTTP API connection
      fortinet.fortimanager.fmgr_pkg_firewall_policy:
        bypass_validation: false
        adom: "root"
        pkg: "Hub1"
        state: "present"
        pkg_firewall_policy: {}
