---
- name: Configure FortiManager Package and Firewall Policies
  hosts: fortimanager
  connection: httpapi
  gather_facts: false
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443

  tasks:
    # Now create the firewall policies
    - name: Configure firewall policies in Hub package
      fortinet.fortimanager.fmgr_firewall_policy:
        adom: "root"
        pkg: "Hub1"
        state: "present"
        firewall_policy: "{{ item }}"
      loop:
        - name: "sd-wan-out"
          policyid: 2
          action: "accept"
          srcintf: ["port1"]
          dstintf: ["overlay"]
          srcaddr: ["all"]
          dstaddr: ["all"]
          service: ["ALL"]
          schedule: ["always"]
          nat: "disable"
          status: "enable"
          logtraffic: "utm"
          profile-protocol-options: "default"
          ssl-ssh-profile: "no-inspection"
          auto-asic-offload: "enable"
          np-acceleration: "enable"

        - name: "sd-wan-in"
          policyid: 3
          action: "accept"
          srcintf: ["overlay"]
          dstintf: ["port1"]
          srcaddr: ["all"]
          dstaddr: ["all"]
          service: ["ALL"]
          schedule: ["always"]
          nat: "disable"
          status: "enable"
          logtraffic: "utm"
          comments: " (Reverse of sd-wan-out)"
          profile-protocol-options: "default"
          ssl-ssh-profile: "no-inspection"
          auto-asic-offload: "enable"
          np-acceleration: "enable"

        - name: "vpn2vpn"
          policyid: 4
          action: "accept"
          srcintf: ["overlay"]
          dstintf: ["overlay"]
          srcaddr: ["all"]
          dstaddr: ["all"]
          service: ["ALL"]
          schedule: ["always"]
          nat: "disable"
          status: "enable"
          logtraffic: "utm"
          profile-protocol-options: "default"
          ssl-ssh-profile: "no-inspection"
          auto-asic-offload: "enable"
          np-acceleration: "enable"
      register: policy_results

    - name: Show policy creation results
      ansible.builtin.debug:
        var: policy_results