---
- name: Configure FortiManager Firewall Policies in Hub Package
  hosts: fortimanager
  connection: httpapi
  gather_facts: false
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443

    firewall_policies:
      - { policyid: 2, name: "sd-wan-out", action: "accept", srcintf: "port1", dstintf: "overlay", srcaddr: "all", dstaddr: "all", service: "ALL", schedule: "always", nat: "disable", status: "enable", logtraffic: "utm", profile_protocol_options: "default", ssl_ssh_profile: "no-inspection", auto_asic_offload: "enable", np_acceleration: "enable" }
      - { policyid: 3, name: "sd-wan-in", action: "accept", srcintf: "overlay", dstintf: "port1", srcaddr: "all", dstaddr: "all", service: "ALL", schedule: "always", nat: "disable", status: "enable", logtraffic: "utm", comments: "(Reverse of sd-wan-out)", profile_protocol_options: "default", ssl_ssh_profile: "no-inspection", auto_asic_offload: "enable", np_acceleration: "enable" }
      - { policyid: 4, name: "vpn2vpn", action: "accept", srcintf: "overlay", dstintf: "overlay", srcaddr: "all", dstaddr: "all", service: "ALL", schedule: "always", nat: "disable", status: "enable", logtraffic: "utm", profile_protocol_options: "default", ssl_ssh_profile: "no-inspection", auto_asic_offload: "enable", np_acceleration: "enable" }

  tasks:
    - name: Create policy package 'Hub1' if it doesn't exist
      fortinet.fortimanager.fmgr_pkg:
        adom: root
        pkg: Hub1
        state: present
        pkg_type: firewall
        
    - name: Create firewall policies in Hub package
      fortinet.fortimanager.fmgr_pkg_firewall_policy:
        bypass_validation: false
        adom: root
        pkg: Hub1
        state: present
        pkg_firewall_policy: "{{ item }}"
      loop: "{{ firewall_policies }}"
      register: policy_results

    - name: Show policy creation results
      ansible.builtin.debug:
        var: policy_results.results
