- hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  
  tasks:
    - name: Delete groups if they exist
      fmgr_dvmdb_group:
        adom: root
        state: absent
        name: "{{ group_names }}"
