- name: Delete all FOS devices from FMG In a specific adom
  hosts: fortimanager
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"
  tasks:
    - name: fetch all devices
      fmgr_fact:
        facts:
            selector: 'dvmdb_device'
            params:
                adom: 'root'
                device: ''
      register: alldevices

    - name: debug message for each device
      debug:
        msg:
         - 'We are going to delete device: {{ item.name }}'
         - 'IP of the device is: {{ item.ip }}'
      loop: "{{ alldevices.meta.response_data }}"
      when: alldevices.meta.response_data != []

    - name: Create The Task To Delete Each Device
      fmgr_dvm_cmd_del_device:
        dvm_cmd_del_device:
            device: '{{ item.name }}'
            adom: 'root'
            flags:
             - 'create_task'
             - 'nonblocking'
      register: uninstalling_task
      loop: "{{ alldevices.meta.response_data }}"
      when: alldevices.meta.response_data != []

    - name: poll the task for each device
      fmgr_fact:
        facts:
            selector: 'task_task'
            params:
                task: '{{ uninstalling_task.meta.response_data.taskid }}'
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5
      failed_when: taskinfo.meta.response_data.state == 'error'
      loop: "{{ alldevices.meta.response_data }}"
      when: alldevices.meta.response_data != []
