- name: Delete all FOS devices from FMG In a specific adom
  hosts: fortimanager
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  tasks:
    - name: fetch all devices
      fmgr_fact:
        facts:
            selector: 'dvmdb_device'
            params:
                adom: 'root'
                device: ''
      register: alldevices

    - name: debug message for each device
      debug:
        msg:
         - 'We are going to delete device: {{ item.name }}'
         - 'IP of the device is: {{ item.ip }}'
      loop: "{{ alldevices.meta.response_data }}"
      when: alldevices.meta.response_data != []

    - name: Create The Task To Delete Each Device
      fmgr_dvm_cmd_del_device:
        dvm_cmd_del_device:
            device: '{{ item.name }}'
            adom: 'root'
            flags:
             - 'create_task'
             - 'nonblocking'
      register: uninstalling_task
      loop: "{{ alldevices.meta.response_data }}"
      when: alldevices.meta.response_data != []

   