- hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  
  tasks:
    - name: Delete groups
      fmgr_dvmdb_group:
        adom: "root"
        state: "absent"
        dvmdb_group:
          name: "{{ group_names }}"

