- hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"
    adom: "root"

  tasks:
    - name: Gather system group facts from FortiManager
      fortinet.fortimanager.fmgr_fact:
        adom: "{{ adom }}"
        facts:
          - system_group
      register: fmgr_groups

    - name: Gather system device facts from FortiManager
      fortinet.fortimanager.fmgr_fact:
        adom: "{{ adom }}"
        facts:
          - system_device
      register: fmgr_devices

    - name: Check if there are more than 2 groups or 1 or more devices
      debug:
        msg: "There are more than 2 groups or 1 or more devices registered in FortiManager."
      when:
        - (fmgr_groups.ansible_fortimanager.system_group | length > 2) or (fmgr_devices.ansible_fortimanager.system_device | length > 0)

    - name: Fail if conditions are met
      fail:
        msg: "There are more than 2 groups or 1 or more devices registered in FortiManager."
      when:
        - (fmgr_groups.ansible_fortimanager.system_group | length > 2) or (fmgr_devices.ansible_fortimanager.system_device | length > 0)
