- hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"
    adom: "root"

  tasks:
    - name: Get list of groups in FortiManager
      fortinet.fortimanager.fmgr_dvmdb_group:
        adom: "{{ adom }}"
        state: "present"  # Correct state argument
      register: groups_response

    - name: Get list of devices in FortiManager
      fortinet.fortimanager.fmgr_dvmdb_device:
        adom: "{{ adom }}"
        state: "present"  # Correct state argument
      register: devices_response

    - name: Check if there are more than 2 groups or 1 or more devices
      fail:
        msg: "There are more than 2 groups or 1 or more devices registered in FortiManager."
      when: 
        - groups_response.results | length >= 2
        - devices_response.results | length > 0
