- hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"
    adom: "root"

  tasks:
    - name: Get device groups
      fortinet.fortimanager.fmgr_fact:
        adom: "{{ adom }}"
        facts:
          selector: "dvmdb_group"
          params:
            fields: ["name", "member"]
      register: group_facts

    - name: Get devices
      fortinet.fortimanager.fmgr_fact:
        adom: "{{ adom }}"
        facts:
          selector: "dvmdb_device"
          params:
            fields: ["name", "sn"]
      register: device_facts

    - name: Check if there are more than 1 groups or 1 or more devices
      fail:
        msg: "There are more than 1 groups or 1 or more devices registered in FortiManager."
      when: 
        - (group_facts.meta.response_data | length > 1) or 
          (device_facts.meta.response_data | length > 0)