- hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"
    adom: "root"

  tasks:
    - name: Gather facts from FortiManager
      fortinet.fortimanager.fmgr_fact:
        adom: "{{ adom }}"
        facts:
          - system_group
          - system_device
      register: fmgr_facts

    - name: Check if there are more than 1 groups or 1 or more devices
      fail:
        msg: "There are more than 1 groups or 1 or more devices registered in FortiManager."
      when:
        - (fmgr_facts.ansible_fortimanager.system_group | length > 1) or (fmgr_facts.ansible_fortimanager.system_device | length > 0)
