- hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"
    adom: "root"
    max_allowed_groups: 1
    max_allowed_devices: 0

  tasks:
    - name: Retrieve all device groups
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: 'dvmdb_group'
          params:
            group: ''
            fields: ['name', 'desc', 'os_type', 'type', 'cluster_type']
            loadsub: 1
            range: [0, 100]
      register: group_facts