- name: Gather FortiManager facts
  hosts: fortimanager
  gather_facts: no  # We're not gathering system facts, just FMG-specific ones
  connection: httpapi
  collections:
    - fortinet.fortimanager
  
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"
  
  tasks:
    - name: Retrieve all device groups
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: 'dvmdb_group'
          params:
            adom: 'root'
            group: '' 
      
      register: group_facts  
    
    - name: Display the gathered group facts
      debug:
        var: group_facts