- name: gathering fortimanager facts
  hosts: fortimanager
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_user: "admin"
    ansible_password: "admin"
    ansible_host: "192.168.10.6"
  tasks:
   - name: retrieve all the groups in the device
     fmgr_fact:
       facts:
           selector: 'dvmdb_group'
           params:
               adom: 'root'
               group: ''