- name: INSTALL PREVIEW - POLICY PACKAGES (Hubs and Spokes)
  hosts: fortimanager
  connection: httpapi
  vars:
    adom: root
    policy_packages:
      - Hubs
      - spokes

  tasks:
    - name: Install for policy package [preview mode] {{ item }}
      fortinet.fortimanager.fmgr_securityconsole_install_package:
        securityconsole_install_package:
          adom: "{{ adom }}"
          flags:
            - cp_all_objs
          pkg: "{{ item }}"
      loop: "{{ policy_packages }}"
      register: install_tasks

    - name: Poll the install tasks
      vars:
        task_id: "{{ item.meta.response_data.task }}"
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: "task_task"
          params:
            task: "{{ task_id }}"
      loop: "{{ install_tasks.results }}"
      loop_control:
        label: "{{ item.item }}"
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5

    - name: Show final preview install result
      debug:
        msg: "{{ taskinfo }}"