- name: Commit config to multiple devices
  hosts: fortimanager
  gather_facts: false
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
    ansible_command_timeout: 120
    ansible_warnings: false
    device_adom: "root"
    device_vdom: "root"
    devices:
      - name: "Hub"
      - name: "spoke1"
      - name: "spoke2"

  tasks:
    - name: Get device object IDs
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: "dvmdb_device"  # Corrected from devprof_device to dvmdb_device
          params:
            adom: "{{ device_adom }}"
            filter: ["name", "in", "{{ devices | map(attribute='name') | list }}"]  # Added filter
      register: device_facts

    - name: Set device object IDs (simplified)
      set_fact:
        device_ids: "{{ device_facts.meta.response_data | map(attribute='oid') | list }}"
        device_names: "{{ device_facts.meta.response_data | map(attribute='name') | list }}"

    - name: Debug device information
      debug:
        msg: |
          Device IDs: {{ device_ids }}
          Device Names: {{ device_names }}

    - name: Invoke the task for all devices
      fortinet.fortimanager.fmgr_securityconsole_install_device:
        securityconsole_install_device:
          adom: "{{ device_adom }}"
          scope: "{{ devices }}"
          flags:
            - none  
      register: installing_task