---
- name: Commit config to multiple devices
  hosts: fortimanager
  gather_facts: false
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
    ansible_command_timeout: 120
    ansible_warnings: false
    device_adom: "root"
    device_vdom: "root"
    devices:
      - name: "Hub"
      - name: "spoke1"
      - name: "spoke2"

  tasks:
    - name: Get device object IDs
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: "dvmdb_device"
          params:
            adom: "{{ device_adom }}"
      register: device_facts
      failed_when: device_facts.rc != 0

    - name: Debug device facts
      debug:
        var: device_facts
      when: device_facts.rc == 0

    - name: Set device object IDs
      set_fact:
        device_ids: "{{ device_facts.meta.response_data | selectattr('name', 'in', devices | map(attribute='name') | list) | map(attribute='oid') | list }}"
      when: device_facts.rc == 0 and device_facts.meta.response_data is defined

    - name: Debug device IDs
      debug:
        var: device_ids
      when: device_ids is defined

    - name: Invoke the task for all devices
      fortinet.fortimanager.fmgr_securityconsole_install_device:
        securityconsole_install_device:
          adom: "{{ device_adom }}"
          scope: "{{ devices }}"
      register: installing_task
      failed_when: installing_task.rc != 0
      when: device_ids is defined and device_ids | length > 0

    - name: Debug installing task
      debug:
        var: installing_task
      when: installing_task.rc == 0

    - name: Inspect the Task Status
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: "task_task"
          params:
            task: "{{ installing_task.meta.response_data.task }}"
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 60
      delay: 5
      failed_when: taskinfo.rc != 0
      when: installing_task.rc == 0 and installing_task.meta.response_data.task is defined

    - name: Debug task status
      debug:
        var: taskinfo
      when: taskinfo.rc == 0

    - name: Reload and retrieve the device list from FortiManager
      fortinet.fortimanager.fmgr_dvm_cmd_reload_devlist:
        workspace_locking_adom: root
        workspace_locking_timeout: 300
        dvm_cmd_reload_devlist:
          adom: "{{ device_adom }}"
          flags:
            - create_task
            - nonblocking
          from: fgfm
          reload_dev_member_list: "{{ device_ids | default([]) }}"
      register: reload_task
      failed_when: reload_task.rc != 0
      when: device_ids is defined and device_ids | length > 0

    - name: Monitor reload task status
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: "task_task"
          params:
            task: "{{ reload_task.response_data.task }}"
      register: reload_taskinfo
      until: reload_taskinfo.meta.response_data.percent == 100
      retries: 60
      delay: 5
      failed_when: reload_taskinfo.rc != 0
      ignore_errors: yes
      when: reload_task.rc == 0