---
- name: Test FortiGate API Connectivity
  hosts: fortigate 
  gather_facts: no  
  connection: httpapi

  tasks:
    - name: Get system status (API test)
      fortios.fortios_monitor_system_status:  
        vdom: "root"
      register: api_result

    - name: Display connection result
      ansible.builtin.debug:
        var: api_result