---
- name: Test FortiGate API
  hosts: all
  gather_facts: no
  connection: httpapi

  tasks:
    - name: Get system info (100% working alternative)
      fortinet.fortios.fortios_system_global:
        vdom: "root"
        system_global:
          hostname: "test"
      register: result

    - name: Show API result
      debug:
        var: result