- name: Add FOS devices to FMG
  hosts: fortimanager
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  tasks:
    - name: Process FortiGate devices
      ansible.builtin.include_tasks: add_single_device.yml
      vars:
        current_ip: "{{ item }}"
      loop: "{{ fos_ip }}"