---
- name: Test FortiGate API Connectivity
  hosts: fortigate
  gather_facts: no
  connection: httpapi

  tasks:
    - name: Get system status
      fortios_monitor_system_status:  
        vdom: "root"
      register: result

    - name: Show result
      debug:
        var: result