---
- name: Test FortiOS API connectivity
  hosts: all
  gather_facts: no
  connection: httpapi

  tasks:
    - name: Get system status
      fortios.fortios_monitor_system_status:
        vdom: "root"
      register: api_result
      
    - name: Show connection result
      debug:
        var: api_result