- name: Reinstall policy package on FortiManager
  hosts: fortimanager
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
  tasks:
    - name: Re-install a policy package that had been previously installed
      fortinet.fortimanager.fmgr_securityconsole_reinstall_package:
        adom: "root"
        pkg: "Spokes"
        workspace_locking_adom: "root"
        workspace_locking_timeout: 300
        target:
          - name: "spoke1"
            vdom: "root"

