---
- name: Reload device list in FortiManager
  hosts: fortimanager
  gather_facts: false
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
    ansible_command_timeout: 300
    ansible_warnings: false
    device_adom: "root"
    devices:
      - name: "Hub"
      - name: "spoke1"
      - name: "spoke2"

  tasks:
    - name: Retrieve a list of devices
      fortinet.fortimanager.fmgr_dvm_cmd_reload_devlist:
        workspace_locking_adom: "{{ device_adom }}"
        workspace_locking_timeout: 300
        dvm_cmd_reload_devlist:
          adom: "{{ device_adom }}"
          flags:
            - "create_task"
            - "nonblocking"
          from: fgfm
          reload_dev_member_list:
            - name: "{{ item.name }}"
      loop: "{{ devices }}"