---
- name: Reload device list in FortiManager
  hosts: fortimanager
  gather_facts: false
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
    ansible_command_timeout: 300
    ansible_warnings: false
    device_adom: "root"
    devices:
      - name: "Hub"
      - name: "spoke1"
      - name: "spoke2"

  tasks:
    - name: Format device member list
      set_fact:
        reload_members: "{{ devices | map(attribute='name') | map('regex_replace', '^(.*)$', '{\"name\": \"\\1\"}') | map('from_yaml') | list }}"

    - name: Debug formatted members
      debug:
        var: reload_members

    - name: Reload device list in FortiManager
      fortinet.fortimanager.fmgr_dvm_cmd_reload_devlist:
        workspace_locking_adom: "{{ device_adom }}"
        workspace_locking_timeout: 600
        dvm_cmd_reload_devlist:
          adom: "{{ device_adom }}"
          flags:
            - create_task
            - nonblocking
          from: fgfm
          reload_dev_member_list: "{{ reload_members }}"
      register: reload_task
      when: reload_members | length > 0

    - name: Wait for the reload task to finish
      fortinet.fortimanager.fmgr_task:
        task_id: "{{ reload_task.meta.response_data.task }}"
      register: reload_status
      until: reload_status.meta.response_data.percent == 100
      retries: 30
      delay: 10

    - name: Show reload task result
      debug:
        var: reload_status

