- name: Configure IPsec VPN in FortiManager
  hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    fmg_adom: "root"
    vpn_name: "Site-to-Site-VPN"
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: fortinet.fortimanager.fortimanager
    fmg_host: "192.168.10.6"
    fmg_username: "admin"
    fmg_password: "root"
    fmg_adom: "root"
    template_name: "testtttt"
    vault_ipsec_psk: "test"

  tasks:
    - name: Configure IPsec VPN
      fortinet.fortimanager.fmgr_firewall_vip:
        adom: "{{ fmg_adom }}"
        state: "present"
        firewall_vip:
          name: "{{ vpn_name }}"
          type: "ipsec"
          extintf: "wan1"
          extip: "0.0.0.0-0.0.0.0"
          extport: "0-65535"
          mappedip:
            - range: "192.168.1.1-192.168.1.254"
          portforward: "disable"
        host: "{{ fmg_host }}"
        username: "{{ fmg_username }}"
        password: "{{ fmg_password }}"
        validate_certs: false

    - name: Configure Phase 1
      fortinet.fortimanager.fmgr_vpn_ipsec_phase1:
        adom: "{{ fmg_adom }}"
        state: "present"
        vpn_ipsec_phase1:
          name: "{{ vpn_name }}-Phase1"
          type: "static"
          interface: "wan1"
          ike-version: "2"
          peertype: "any"
          net-device: "disable"
          proposal: "aes256-sha256"
          psksecret: "{{ vault_psk }}"
          dpd: "on-demand"
          remote-gw: "203.0.113.5"  # Replace with peer IP
        host: "{{ fmg_host }}"
        username: "{{ fmg_username }}"
        password: "{{ fmg_password }}"
        validate_certs: false

    - name: Configure Phase 2
      fortinet.fortimanager.fmgr_vpn_ipsec_phase2:
        adom: "{{ fmg_adom }}"
        state: "present"
        vpn_ipsec_phase2:
          name: "{{ vpn_name }}-Phase2"
          phase1name: "{{ vpn_name }}-Phase1"
          proposal: "aes256-sha1"
          pfs: "enable"
          replay: "enable"
          keepalive: "enable"
        host: "{{ fmg_host }}"
        username: "{{ fmg_username }}"
        password: "{{ fmg_password }}"
        validate_certs: false